language: node_js
node_js:
  - 8.9.1
cache:
  directories:
    - "node_modules"
deploy:
  provider: heroku
  strategy: git
  app: pubg-webapp
  api_key:
    secure: o7PF0Xtg69D0sGOESNVSQlK0jgNM72U4wbDDz7Zy0u5uwCScLzHQgXY8uEQM7EpiUSZLbpHCL4ZeTvrkETa0bCEzQL574g91OA1MKI4x8FOAzyLMzXy/XermlIfjnkTmEzJoyApC3aWF7n19Z65CDinOshUcyRGvqSxyGULo0mDVzO4P00YMZRbohqYmGootlv3UNXOOKBZJ1HlnguiGMSZ4CpQQT8hj7vb4RuRoeYxEvPTYKG6EJy8LzN/SnRVvyHYrTooKFmNWMpqlLPF6ua6idW8/3wkq6O9e2paYt+ZEUx9+e54Hr4iG2hmvKzKG9dqmOMnO2xN3wtU4Nl5uEyeuhPNlXAUB3ZQSYz+Z5/N9wM562jpid0aEUDawOVCaz2d7Qps9ZdoWBebM+fyvia5+CoQ/pQI7BJGcXP2S73WoyksrQZxZnL8nYCuJne+0/FCLGbwudstjEsiIyW92TUXtIkX6Lqd23eeO/+EuzwoRJvqWAbflfLaFWqJ5qYZSg6LVrX+QkUYVP96Vh+99qQlOXhDXkptbZzZpusBiSbNy02ngF0CdxFK4Y4nntr26fkVy43kgTWPQ7DUcw0pcoRKCBOYlTPSGk7D8ipv+kdY33MO2n/lbHMTUHL0TjtftvmUwc/4aItoVM80TJgH5xH9C2CokTgrAwnp8Cbu0CV0=
  on:
    repo: lucas-rds/webapp
    all_branches: true
